image: gcc

stages:
  - build
  - version
  - deploy

build:
  stage: build
  timeout: 3h
  script:
    - apt update -y && apt install -y cmake ninja-build
    - export VCPKG_BINARY_SOURCES="clear;files,$CI_PROJECT_DIR/vcpkg_cache,readwrite"
    - mkdir -p build
    - cd build
    # - ln -s /usr/bin/ninja /usr/bin/ninja-build
    - cmake -G Ninja .. 
    - ninja
    - cd ..
  cache:
    key: vcpkg_cache
    when: 'always'
    paths:
      - vcpkg_cache/
  artifacts:
    # when: always
    paths:
      - vcpkg/buildtrees/*/*.log
      - vcpkg/buildtrees/*/*/*.log
      - vcpkg/buildtrees/*/*/*/*.log
      - vcpkg/buildtrees/*/*/*/*/*.log
      - vcpkg/buildtrees/*/*/*/*/*/*.log
      - vcpkg/buildtrees/*/*/*/*/*/*/*.log
      - vcpkg/buildtrees/*/*/*/*/*/*/*/*.log
      - vcpkg/buildtrees/*/*/*/*/*/*/*/*/*.log
      - vcpkg/buildtrees/*/*/*/*/*/*/*/*/*/*.log
      - vcpkg/buildtrees/*/*/*/*/*/*/*/*/*/*/*.log
      # - build/vcpkg_installed/
