image: registry.git.rwth-aachen.de/leander.schulten/lichtsteuerung/build_qt_5.15.2:latest

stages:
  - build
  - version
  - deploy

build:
  stage: build
  script:
    - git submodule update --init --recursive
    - rm -rf vcpkg/packages vcpkg/buildtrees
    - CC=/usr/bin/gcc
    - CXX=/usr/bin/g++
    - export VCPKG_BINARY_SOURCES="clear;files,$CI_PROJECT_DIR/vcpkg_cache,readwrite"
    - ./vcpkg/bootstrap-vcpkg.sh
    - cp x64-linux-windows-static.cmake ./vcpkg/triplets/community
    # - sed -i /CMAKE_MODULE_PATH/d $CMAKE_TOOLCHAIN_FILE
    - cat $CMAKE_TOOLCHAIN_FILE
    - sed -i "s/find_path(Boost_INCLUDE_DIR/find_path(Boost_INCLUDE_DIR NO_CMAKE_FIND_ROOT_PATH/" /usr/src/mxe/usr/x86_64-pc-linux-gnu/share/cmake-3.19/Modules/FindBoost.cmake
    - cat /usr/src/mxe/usr/x86_64-pc-linux-gnu/share/cmake-3.19/Modules/FindBoost.cmake
    # - unset CMAKE_TOOLCHAIN_FILE
    # - ./vcpkg/vcpkg install --triplet=x64-linux-windows-static --feature-flags=manifests
    - cd src/lib
    - ./build_libs.sh
    - cd ../..
    - mkdir -p build
    - cd build
    - cmake -G Ninja .. -DVCPKG_TARGET_TRIPLET=x64-linux-windows-static
    - ninja
    - cd ..
  cache:
    key: vcpkg_cache
    paths:
      - vcpkg_cache/
  artifacts:
    when: always
    paths:
      - build/src/lichtsteuerung.exe
      - build/vcpkg-manifest-install.log
      - vcpkg/buildtrees/aubio/
      # - vcpkg/buildtrees/libbacktrace
      # - build/vcpkg_installed/

# we use this version file to check if a new version exists 
version:
  stage: version
  only:
    refs:
      - windows-release
  script:
    - echo $(git rev-parse --short HEAD) > version.txt
  artifacts:
    name: version
    paths:
      - version.txt


deploy:
  stage: deploy
  only:
    refs:
      - windows-release
  script: 
    - cp build/release/Lichtsteuerung.exe windows-release
    - mkdir -p windows-release/modulesHeader
    - cp -r src/modules windows-release/modulesHeader
    - echo "includePath=modulesHeader" >> windows-release/settings.ini
#   - echo "moduleDirPath=modules" >> windows-release/settings.ini
    - cp version.txt windows-release
  artifacts:
    paths:
      - windows-release
