image: registry.git.rwth-aachen.de/leander.schulten/lichtsteuerung/build_5.14.2:latest

stages:
  - build
  - version
  - deploy

build:
  stage: build
  script:
    - cd src/lib
    - ./build_libs.sh
    - cd ../..
    - mkdir -p build
    - cd build
    - /usr/src/mxe/usr/x86_64-w64-mingw32.shared.posix/qt5/bin/qmake ../src/Lichtsteuerung.pro
    - make -j$(nproc)
    - cd ..
  cache:
    key: build_boost
    paths:
      - src/lib/boost/
  artifacts:
    paths:
      - build/release/Lichtsteuerung.exe

# we use this version file to check if a new version exists 
version:
  stage: version
  only:
    refs:
      - windows-release
  script:
    - echo $(git rev-parse --short HEAD) > version.txt
  artifacts:
    name: version
    paths:
      - version.txt


deploy:
  stage: deploy
  only:
    refs:
      - windows-release
  script: 
    - cp build/release/Lichtsteuerung.exe windows-release
    - mkdir -p windows-release/modulesHeader
    - cp -r src/modules windows-release/modulesHeader
    - echo "includePath=modulesHeader" >> windows-release/settings.ini
#   - echo "moduleDirPath=modules" >> windows-release/settings.ini
    - cp version.txt windows-release
  artifacts:
    paths:
      - windows-release
