image: registry.git.rwth-aachen.de/leander.schulten/lichtsteuerung/build_qt_5.15.2-shared-without-wine-with-gcc-10

stages:
  - build
  - version
  - deploy

build:
  stage: build
  timeout: 3h
  script:
    - git submodule update --init --recursive
    - rm -rf vcpkg/packages vcpkg/buildtrees
    - CC=/usr/bin/gcc-10
    - CXX=/usr/bin/g++-10
    - export VCPKG_BINARY_SOURCES="clear;files,$CI_PROJECT_DIR/vcpkg_cache,readwrite"
    - ./vcpkg/bootstrap-vcpkg.sh
    - cp x64-linux-windows-static.cmake ./vcpkg/triplets/community
    #- ./vcpkg/vcpkg install --triplet=x64-linux-windows-static --feature-flags=manifests
    - cd src/lib
    - ./build_libs.sh
    - cd ../..
    - mkdir -p build
    - cd build
    - ln -s /usr/bin/ninja /usr/bin/ninja-build
    - ninja --version
    - cmake --version
    - cmake -G Ninja .. -DVCPKG_TARGET_TRIPLET=x64-linux-windows-static
    - ninja
    - cd ..
  cache:
    key: vcpkg_cache
    when: 'always'
    paths:
      - vcpkg_cache/
  artifacts:
    when: always
    paths:
      - build/src/lichtsteuerung.exe
      - vcpkg/buildtrees/harfbuzz/
      - vcpkg/buildtrees/*/*.log
      - vcpkg/buildtrees/*/*/*.log
      - vcpkg/buildtrees/*/*/*/*.log
      - vcpkg/buildtrees/*/*/*/*/*.log
      - vcpkg/buildtrees/*/*/*/*/*/*.log
      - vcpkg/buildtrees/*/*/*/*/*/*/*.log
      - vcpkg/buildtrees/*/*/*/*/*/*/*/*.log
      - vcpkg/buildtrees/*/*/*/*/*/*/*/*/*.log
      - vcpkg/buildtrees/*/*/*/*/*/*/*/*/*/*.log
      - vcpkg/buildtrees/*/*/*/*/*/*/*/*/*/*/*.log
      # - build/vcpkg_installed/

# we use this version file to check if a new version exists 
version:
  stage: version
  only:
    refs:
      - windows-release
  script:
    - echo $(git rev-parse --short HEAD) > version.txt
  artifacts:
    name: version
    paths:
      - version.txt


deploy:
  stage: deploy
  only:
    refs:
      - windows-release
  script: 
    - cp build/release/Lichtsteuerung.exe windows-release
    - mkdir -p windows-release/modulesHeader
    - cp -r src/modules windows-release/modulesHeader
    - echo "includePath=modulesHeader" >> windows-release/settings.ini
#   - echo "moduleDirPath=modules" >> windows-release/settings.ini
    - cp version.txt windows-release
  artifacts:
    paths:
      - windows-release
