set(VCPKG_POLICY_MISMATCHED_NUMBER_OF_BINARIES enabled)

file(INSTALL "${CMAKE_CURRENT_LIST_DIR}/headers/" DESTINATION "${CURRENT_PACKAGES_DIR}/include")

file(INSTALL "${CMAKE_CURRENT_LIST_DIR}/lib/${VCPKG_TARGET_ARCHITECTURE}/" DESTINATION "${CURRENT_PACKAGES_DIR}/lib" FILES_MATCHING PATTERN "*.lib")
file(INSTALL "${CMAKE_CURRENT_LIST_DIR}/lib/${VCPKG_TARGET_ARCHITECTURE}/" DESTINATION "${CURRENT_PACKAGES_DIR}/bin" FILES_MATCHING PATTERN "*.dll")

file(INSTALL "${CMAKE_CURRENT_LIST_DIR}/cmake/" DESTINATION "${CURRENT_PACKAGES_DIR}/share/${PORT}")

file(WRITE "${CURRENT_PACKAGES_DIR}/share/${PORT}/copyright" "See https://git.rwth-aachen.de/leander.schulten/SusbDMX-Driver\n")
