name: Add Artifacts to Release

on:
  release:
    types: [created]

jobs:
  add-artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Wait for Build
        uses: NathanFirmo/wait-for-other-action@v1.0.4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          workflow: cmake.yaml

      - name: Download artifact from build workflow
        uses: dawidd6/action-download-artifact@v6
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: cmake.yaml
          workflow_conclusion: success
          name: windows-build-artifact
          path: windows-artifact

      - name: Download artifact from build-windows-installer workflow
        uses: dawidd6/action-download-artifact@v6
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: build-windows-installer.yaml
          workflow_conclusion: success
          name: windows-installer
          path: windows-artifact


      - name: Get tag and commit info
        run: |
          echo "${{ github.event.release.tag_name }}" > version.txt
          cp version.txt windows-artifact
        shell: bash

      - name: Zip Windows artifact
        run: zip -r windows-artifact.zip windows-artifact

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./windows-artifact.zip
          asset_name: Lichtsteuerung-windows-x64.zip
          asset_content_type: application/zip
