name: Build CMake Project

on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "**"
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        cmake-generator: [Ninja]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up vcpkg and install dependencies
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgGitCommitId: 9b75e789ece3f942159b8500584e35aafe3979ff

      - name: Setup Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: 6.6
          modules: "qtnetworkauth qtwebsockets qt5compat qtshadertools"

      - uses: lukka/get-cmake@latest

      - name: Run CMake+vcpkg+Ninja to build packages and generate/build the code.
        uses: lukka/run-cmake@v10
        with:
          configurePreset: "ninja-multi-vcpkg"
          buildPreset: "ninja-vcpkg-release"

      - name: Run windows deploy script
        if: matrix.os == 'windows-latest'
        run: bash ./deployWindows.sh builds/ninja-multi-vcpkg dest

      - name: Upload build artifact
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v4
        with:
          name: windows-build-artifact
          path: dest
